---
- hosts: all
  become: true
  tasks:
    - name: install tools
      yum:
        name:
          - yum-utils
          - wget
          - git
        state: present
        update_cache: true

    - name: install java
      yum:
        name: java-17-openjdk
        state: present

    - name: install maven
      yum:
        name: maven
        state: present
    - name: git clone
      shell: |
        git clone https://github.com/ganesh-redy/harness-mig-java-lb-healt.git /root/java

    - name: maven create
      shell: |
        cd /root/java && mvn clean package

    - name: check file and local files
      shell: |
        ls /root/java
        echo "\n"
        echo "=============================================" 
        ls -la /root/java/target
      register: list_files

    - name: output of files
      debug:
        msg: "{{ list_files.stdout }}"

    - name: run java program
      shell: |
        cd /root/java && nohup java -jar target/*.jar &
